# Generated by Django 4.1.2 on 2022-10-25 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255, verbose_name='نام نویسنده')),
                ('author_thumb_image', models.ImageField(blank=True, null=True, upload_to='thumb_authors', verbose_name='تصویر نویسنده')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('thumb_image', models.ImageField(blank=True, null=True, upload_to='thumbs', verbose_name='تصویر  جلد کتاب')),
                ('summery', models.TextField(blank=True, null=True, verbose_name='خلاصه')),
                ('review', tinymce.models.HTMLField()),
                ('authors', models.ManyToManyField(to='bookshelf.author', verbose_name='نویسندگان')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب ها',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='نام دسته')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته ها',
            },
        ),
        migrations.CreateModel(
            name='Interpreter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpreter_name', models.CharField(max_length=255, verbose_name='نام مترجم')),
                ('interpreter_thumb_image', models.ImageField(blank=True, null=True, upload_to='thumb_authors', verbose_name='تصویر مترجم')),
            ],
            options={
                'verbose_name': 'مترجم',
                'verbose_name_plural': 'مترجمان',
            },
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='نام کلید')),
            ],
            options={
                'verbose_name': 'کلید واژه',
                'verbose_name_plural': 'کلید واژگان',
            },
        ),
        migrations.CreateModel(
            name='BookAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_assignment', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ واگذاری')),
                ('date_of_return', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بازگرداندن')),
                ('date_of_return_jalali', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='تاریخ بازگرداندن جلالی')),
                ('is_this_book_returned', models.BooleanField(default=False, editable=False, verbose_name='آیا کتاب بازگردانده شده؟')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.book', verbose_name='کتاب')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='قرض گیرنده')),
            ],
            options={
                'verbose_name': 'واگذاری',
                'verbose_name_plural': 'واگذاری',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(to='bookshelf.category', verbose_name='دسته ها'),
        ),
        migrations.AddField(
            model_name='book',
            name='keywords',
            field=models.ManyToManyField(to='bookshelf.keyword', verbose_name='کلمات کلیدی'),
        ),
    ]
