# Generated by Django 4.1.2 on 2022-10-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_demo',
            field=models.FileField(blank=True, null=True, upload_to='pdf_demo', verbose_name='دموی کتاب'),
        ),
        migrations.AddField(
            model_name='book',
            name='pdf_source',
            field=models.FileField(blank=True, null=True, upload_to='pdf_source', verbose_name='فایل اصلی کتاب'),
        ),
    ]
