# Generated by Django 4.1.2 on 2022-10-25 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_imagegallery_options_and_more'),
        ('bookshelf', '0002_book_pdf_demo_book_pdf_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='thumb_image',
        ),
        migrations.AddField(
            model_name='book',
            name='on_paper_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.imagegallery', verbose_name='تصویر جلد کتاب'),
        ),
    ]
