# Generated by Django 4.1.2 on 2022-10-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255, verbose_name='image name')),
                ('image_alt', models.CharField(max_length=255, verbose_name='image alt')),
                ('image_src', models.ImageField(upload_to='image_gallery', verbose_name='image src')),
                ('image_thumb', models.ImageField(blank=True, default='default.jpg', editable=False, upload_to='image_gallery/thumbnail', verbose_name='image thumbnail')),
            ],
            options={
                'verbose_name': 'Image Gallery',
                'verbose_name_plural': 'Images Gallery',
            },
        ),
    ]
