# Generated by Django 4.1.2 on 2022-10-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'verbose_name': 'گالری تصاویر', 'verbose_name_plural': 'گالری تصاویر'},
        ),
        migrations.AlterField(
            model_name='imagegallery',
            name='image_src',
            field=models.ImageField(upload_to='image_gallery/', verbose_name='image src'),
        ),
    ]
